:: Disable unnecessary devices
DevManView.exe /disable "AMD PSP"
DevManView.exe /disable "AMD SMBus"
DevManView.exe /disable "Base System Device"
DevManView.exe /disable "*Bluetooth*" /use_wildcard
DevManView.exe /disable "Composite Bus Enumerator"
DevManView.exe /disable "High precision event timer"
DevManView.exe /disable "Intel Management Engine"
DevManView.exe /disable "Intel SMBus"
DevManView.exe /disable "Microsoft Hyper-V NT Kernel Integration VSP"
DevManView.exe /disable "Microsoft Hyper-V PCI Server"
DevManView.exe /disable "Microsoft Hyper-V Virtual Disk Server"
DevManView.exe /disable "Microsoft Hyper-V Virtual Machine Bus Provider"
DevManView.exe /disable "Microsoft Hyper-V Virtualization Infrastructure Driver"
DevManView.exe /disable "Microsoft Kernel Debug Network Adapter"
DevManView.exe /disable "Microsoft RRAS Root Enumerator"
DevManView.exe /disable "Motherboard resources"
DevManView.exe /disable "NDIS Virtual Network Adapter Enumerator"
DevManView.exe /disable "Numeric Data Processor"
DevManView.exe /disable "PCI Data Acquisition and Signal Processing Controller"
DevManView.exe /disable "PCI Encryption/Decryption Controller"
DevManView.exe /disable "PCI Memory Controller"
DevManView.exe /disable "PCI Simple Communications Controller"
DevManView.exe /disable "SM Bus Controller"
DevManView.exe /disable "System CMOS/real time clock"
DevManView.exe /disable "System Speaker"
DevManView.exe /disable "System Timer"
DevManView.exe /disable "UMBus Root Bus Enumerator"
DevManView.exe /disable "WAN Miniport (IKEv2)"
DevManView.exe /disable "WAN Miniport (IP)"
DevManView.exe /disable "WAN Miniport (IPv6)"
DevManView.exe /disable "WAN Miniport (L2TP)"
DevManView.exe /disable "WAN Miniport (Network Monitor)"
DevManView.exe /disable "WAN Miniport (PPPOE)"
DevManView.exe /disable "WAN Miniport (PPTP)"
DevManView.exe /disable "WAN Miniport (SSTP)"